### PR TITLE
fix: og preview

### LINKED ISSUE #840: fix: og preview
New updates on head repo.
https://github.com/vuejs/docs/commit/658ed80724462e5f8811a504a5881c7dd5604d03

### PR DESCRIPTION
**Pull request by edimitchel**
resolves #840
Cherry picked from https://github.com/vuejs/docs/commit/658ed80724462e5f8811a504a5881c7dd5604d03

### CODE REVIEW

File: .vitepress/config.ts [hunk 1]
```diff
@@ -624,15 +624,25 @@ export default defineConfigWithTheme<ThemeConfig>({
 
   head: [
     ['meta', { name: 'theme-color', content: '#3c8772' }],
-    ['meta', { name: 'twitter:site', content: '@vuejs' }],
-    ['meta', { name: 'twitter:card', content: 'summary' }],
+    ['meta', { property: 'og:url', content: 'https://vuejs.org/' }],
```
Comment (edimitchel) [inline .vitepress/config.ts:627]:
```suggestion
    ['meta', { property: 'og:url', content: 'https://fr.vuejs.org/' }],
```

File: .vitepress/config.ts [hunk 2]
```diff
@@ -624,15 +624,25 @@ export default defineConfigWithTheme<ThemeConfig>({
...
+    ['meta', { property: 'og:type', content: 'website' }],
+    ['meta', { property: 'og:title', content: 'Vue.js' }],
     [
       'meta',
       {
-        name: 'twitter:image',
+        property: 'og:description',
+        content: 'Vue.js - The Progressive JavaScript Framework'
```
Comment (edimitchel) [inline .vitepress/config.ts:634]:
```suggestion
        content: 'Vue.js - Le Framework JavaScript Évolutif'
```

File: .vitepress/config.ts [hunk 3]
```diff
@@ -624,15 +624,25 @@ export default defineConfigWithTheme<ThemeConfig>({
...
+      }
+    ],
+    [
+      'meta',
+      {
+        property: 'og:image',
         content: 'https://vuejs.org/images/logo.png'
```
Comment (edimitchel) [inline .vitepress/config.ts:641]:
```suggestion
        content: 'https://fr.vuejs.org/images/logo.png'
```
